dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
script:
  - python -m pytest
  - find scorevideo_lib -name *.py | xargs pylint
  - find tests/src -name *.py | xargs pylint
  - python -m mypy scorevideo_lib
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master